services:
  - type: web
    name: gideonkamau
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn Gideon.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Gideon.settings
    staticPublishPath: staticfiles
